### ISSUE TITLE
cardano-testnet refactoring

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [input-output-hk/cardano-node#4571]
## What

Refactor the current cardano-testnet tool to perform better and allow for easier configuration of the testnet parameters.

## Why 

Currently we provide scripts that allow for an "easy" deployment of private testnets. Tweaking scripts to test different network settings is not ideal. 

Dapp developers should be able to easily configure and deploy private testnets for their developments. 

## Benefits by persona

Dapp Developers: Have a reliable way to deploy and replicate private testnets so that they can focus on building their applications.

## TASKS

- [ ] [Adjust cardano-testnet executable directory structure ](https://github.com/input-output-hk/cardano-node/issues/4558)
- [x] https://github.com/input-output-hk/cardano-node/issues/4539
- [ ] https://github.com/input-output-hk/cardano-node/issues/4134

**Comment by Jimbo4350** [comment]
Subsumed by #4598
